apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Release.Namespace }}
    name: {{ include "web-app.fullname" . }}
    labels:
    {{- include "web-app.labels" . | nindent 6 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        -   port: {{ .Values.service.port }}
            protocol: TCP
    selector:
    {{- include "web-app.selectorLabels" . | nindent 6 }}
